Add minutes from editorial sessions
solid/specification pull request #307
Opened 2021-09-01 11:52 UTC by justinwb

Per the agreement by editors in the editorial session on 8/31, creating a place to store minutes  from editorial sessions moving forward, and adding minutes from previous sessions.

*Note: Some minutes from older sessions (especially from previous years) may not be included. Editors - please add if you have them.*

2021-09-01 20:20 UTC, kjetilk approved these changes
I'll trust you on this, @justinwb , since you've been very diligent getting the hackmd up for every session!

2021-09-02 12:29 UTC, csarven requested changes
There were a few missing dates in the content. Better to have those in so that if/when the files are relocated (losing {date}.md), the content will retain the date.

2021-09-02 12:29 UTC, csarven commented on meetings/2020-09-04.md
> +September 4th, 2020
```suggestion
Date: 2020-09-04
```

2021-09-02 12:29 UTC, csarven commented on meetings/2020-11-19.md
> +2020-11-19
```suggestion
Date: 2020-11-19
```

2021-09-02 12:29 UTC, csarven commented on meetings/2020-11-30.md
> +November 30th, 2020
```suggestion
Date: 2020-11-30
```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-01-04.md
> +January 4th, 2021
```suggestion
Date: 2021-09-04

```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-02-16.md
> +February 16th, 2021
```suggestion
Date: 2021-02-16
```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-03-02.md
> +March 2nd, 2021
```suggestion
Date: 2021-03-02
```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-04-06.md
> +April 6th, 2021
```suggestion
Date: 2021-04-06
```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-04-22.md
> +Date: 2021-04-22
```suggestion
Date: 2021-04-22
```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-05-04.md
> +May 4th, 2021
```suggestion
Date: 2021-05-04
```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-06-01.md
> +June 1st, 2021
```suggestion
Date: 2021-06-01
```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-06-15.md
> +June 15th, 2021
```suggestion
Date: 2021-06-15
```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-06-22.md
> +DateTime: 2021-06-22T12:00:00Z
```suggestion
Date: 2021-06-22

```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-06-29.md
> +June 29th, 2021
```suggestion
Date: 2021-06-29
```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-07-06.md
> +July 6th, 2021
```suggestion
Date: 2021-07-06
```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-07-20.md
> +
```suggestion
Date: 2021-07-20

```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-08-03.md
> +
```suggestion
Date: 2021-08-03

```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-08-10.md
> +
```suggestion
Date: 2021-08-10

```

2021-09-02 12:29 UTC, csarven commented on meetings/2021-08-31.md
> +August 31st, 2021
```suggestion
2021-08-31
```

2021-09-02 12:33 UTC, csarven approved these changes

2021-09-02 22:11 UTC, csarven commented
Oh.. forgot to mention: the minutes should not be available under solidproject.org/TR/ - that's reserved for technical reports. I don't know where else would be more suitable - perhaps for the time being, it only needs to be available from GitHub.

2021-09-02 22:53 UTC, kjetilk commented
> Oh.. forgot to mention: the minutes should not be available under solidproject.org/TR/ - that's reserved for technical reports. I don't know where else would be more suitable - perhaps for the time being, it only needs to be available from GitHub.

The main idea was to have them on a pod, right?

2021-09-02 23:02 UTC, csarven commented
Yes, I just meant the /path/to/minutes/

Perhaps we use something like `/minutes/{team, panel, ..}/`

2021-09-08 15:22 UTC, kjetilk approved these changes

2021-09-15 10:35 UTC, merged