Update test-report-description test-case-description test-assertion-desrciption
solid/specification pull request #510
Opened 2023-03-15 13:13 UTC by csarven

Follows action of https://github.com/solid/test-suite-panel/blob/main/meetings/2023-02-21.md#specify-requirements-and-criteria-for-publishing-test-summaries-and-reports

2023-03-15 13:38 UTC, michielbdejong approved these changes
Awesome work! <3

2023-03-15 18:26 UTC, TallTed requested changes
Just a couple of minor tweaks

2023-03-15 18:26 UTC, TallTed commented on ED/qa.html
> +                  <p>Test reports MUST incorporate additional information about test criterion indicating test authors and reviewers, review status, version of the test criterion, software and setup
```suggestion
                  <p>Test reports MUST incorporate additional information about test criteria indicating test authors and reviewers, review status, version of the test criterion, software and setup used to run the tests, provenance and coverage and test suite (see also <a href="#test-assertion-description">Test Assertion Description</a>).</p>
```

2023-03-15 18:26 UTC, TallTed commented on ED/qa.html
> +                      <p>To help distinguish test criterions, it is encouraged to use versioned URIs for criterions.</p>
```suggestion
                      <p>To help distinguish test criteria, it is encouraged to use versioned URIs for criteria.</p>
```

2023-03-21 08:51 UTC, edwardsph approved these changes
Great - thanks. Just a few minor suggestions.

2023-03-21 08:51 UTC, edwardsph commented on ED/qa.html
> +                  <p>Test reports with approved status MUST NOT include test assertions with rejected review status (<code>td:rejected</code>).</p>
```suggestion
                  <p>Test reports with approved status MUST NOT include assertions related to test criteria with rejected review status (<code>td:rejected</code>).</p>
```
The assertion doesn't have a status, the test itself does.

2023-03-21 08:51 UTC, edwardsph commented on ED/qa.html
> +                      <p>To convey association between a test criterion and their reviews, it is encouraged to use the <a href="https://www.w3.org/TR/annotation-vocab/">Web Annotation Vocabulary</a>
```suggestion
                      <p>To convey association between a test criterion and its reviews, it is encouraged to use the <a href="https://www.w3.org/TR/annotation-vocab/">Web Annotation Vocabulary</a> with the <code>oa:assessing</code> motivation.</p>
```

2023-03-21 08:51 UTC, edwardsph commented on ED/qa.html
> +                  <p class="issue">Should <a href="https://www.w3.org/TR/annotation-vocab/">Web Annotation Vocabulary</a> be required to convey the relationship between test criterion and reviews?</p
```suggestion
                  <p class="issue">Should <a href="https://www.w3.org/TR/annotation-vocab/">Web Annotation Vocabulary</a> be required to convey the relationship between test criteria and reviews?</p>
```

2023-03-21 13:44 UTC, merged

2023-03-21 13:44 UTC, csarven commented
Merged as per agreement in 2023-03-21 meeting: https://github.com/solid/test-suite-panel/pull/18