Add 2023-03-15 agenda and minutes
solid/specification pull request #511
Opened 2023-03-15 13:42 UTC by csarven

Request to merge in 24 hours following meeting.

2023-03-15 19:08 UTC, TallTed requested changes
Mostly minor. Moves away from poor-person's HTML/Markdown.

2023-03-15 19:08 UTC, TallTed commented on meetings/2023-03-15.md
> +* eP: It links back to another relevant issue about CLI clients: https://github.com/solid/data-interoperability-panel/issues/178
```suggestion
* eP: It links back to [another relevant issue about CLI clients](https://github.com/solid/data-interoperability-panel/issues/178)
```

2023-03-15 19:08 UTC, TallTed commented on meetings/2023-03-15.md
> +* SC: Specify kind of actors and class of interactions: https://github.com/solid/specification/issues/36 (c. 2019)
```suggestion
* SC: [Specify kind of actors and class of interactions](https://github.com/solid/specification/issues/36) (circa 2019)
```

2023-03-15 19:08 UTC, TallTed commented on meetings/2023-03-15.md
> +* SC: there has been wok on this topic over the past few years, but eP is helping to move this issue further. Question: will we look at server-to-server interoperability. Most conversations have been
```suggestion
* SC: there has been work on this topic over the past few years, but eP is helping to move this issue further. Question: will we look at server-to-server interoperability? Most conversations have been on client-server, but server-to-server interaction is increasingly important (as expected).
```

2023-03-15 19:08 UTC, TallTed commented on meetings/2023-03-15.md
> +* SC: This is a great example of this issue. So far that pattern has been in an implementation (e.g., NSS) but not specified. Along with ACLs having own ACLs. The WAC spec for example does not constr
```suggestion
* JZ: I recall you can have a ACL on a `describedby` resource. Is this still part of the discussion?
* SC: This is a great example of this issue. So far that pattern has been in an implementation (e.g., NSS) but not specified. Along with ACLs having their own ACLs. For example, the WAC spec does not constrain which resources can have an ACL — so any resource can. We need to clarify this in the Solid Protocol, as there are cases in which the controls on the primary resource and the associated resource are separated. See issue for some examples.
```

2023-03-15 19:08 UTC, TallTed commented on meetings/2023-03-15.md
> +* AD: How complex is this going to be for users - with what Solid provides. Solid has many topics, .. so end user using some component, so is the complexity going to be too much for them or some abst
```suggestion
* eP: I think we can't avoid paying attention to UX patterns that might be required. If we expect end users to manage access policies, we need to provide them with something that an average (non-geek) person can manage in a responsible way.
* AD: How complex is this going to be for users — with what Solid provides? Solid has many topics, ... so end user using some component, is the complexity going to be too much for them, or some abstraction that simplifies it for them? Especially using different applications that may not be uniform, it'd be difficult.
```

2023-03-15 19:08 UTC, TallTed commented on meetings/2023-03-15.md
> +* eP: I'm happy to share some of the approach we took in the SAI spec. We could have short agenda point next week. SAI: https://solid.github.io/data-interoperability-panel/specification/
```suggestion
* SC: WAC authorization model is designed to simplify (e.g., meant to be basic read/write/control). Users may also think in more of a workflow perspective, such as review of item.
* eP: I'm happy to share some of the approach we took in [the SAI spec](https://solid.github.io/data-interoperability-panel/specification/). We could have a short agenda point next week.
```

2023-03-16 12:43 UTC, csarven commented on meetings/2023-03-15.md
> +* [Join the W3C Solid Community Group](https://www.w3.org/community/solid/join), [W3C Account Request](http://www.w3.org/accounts/request), [W3C Community Contributor License Agreement]( )
It apparently changed during the meeting. We mentioned CLA briefly so someone must've cut the text instead of copy. Thanks for catching that.

2023-03-17 06:39 UTC, merged