Add discovery and descriptions for implementation report, test suite, test case
solid/specification pull request #542
Opened 2023-07-17 12:17 UTC by csarven

Follows actions of https://github.com/solid/test-suite-panel/blob/main/meetings/2023-05-16.md

* Update technical-report-description (for the discovery of implementation report and test suite)
* Update test-suite-description (for the discovery of test cases)
* Add implementation-report-description

2023-07-18 13:44 UTC, edwardsph approved these changes
LGTM

2023-07-19 22:36 UTC, kjetilk approved these changes
LGTMT

2023-07-20 18:28 UTC, TallTed requested changes
tiny but important

2023-07-20 18:28 UTC, TallTed commented on ED/qa.html
> +                  <p class="issue">Defining URI Templates for implementation report, e.g.,<code>https://solidproject.org/test-reports/{technical-report-short-name}/summary</code>, and test report, e.
```suggestion
                  <p class="issue">Defining URI Templates for implementation report, e.g., <code>https://solidproject.org/test-reports/{technical-report-short-name}/summary</code>, and test report, e.g., <code>https://solidproject.org/test-reports/{technical-report-short-name}/{uuid}</code></p>
```

2023-07-24 13:22 UTC, merged