Add 2023-07-26 agenda and minutes
solid/specification pull request #547
Opened 2023-07-26 12:28 UTC by csarven

Request to merge in 24 hours following meeting.

2023-07-26 17:16 UTC, TallTed requested changes
the usual

2023-07-26 17:16 UTC, TallTed commented on meetings/2023-07-26.md
> +* SC: Here are two proposals but let's get other feedback or alternative proposals before deciding anything.
```suggestion
* SC: Raised by MC that folks may be on holidays. Last call: 2023-07-25, Approval: (after) 2023-08-01 dates were proposed (https://github.com/solid/process/pull/323#issuecomment-1629875377). This was accepted in prior calls. WT hinted at 28 days being sufficient in recent comments and extending further may not particularly help considering current state.
* SC: Reviews seem sufficient to me but always welcome to have more representation, so getting more reviews would be great.
* SC: Here are two proposals, but let's get other feedback or alternative proposals before deciding anything.
```

2023-07-26 17:16 UTC, TallTed commented on meetings/2023-07-26.md
> +* SC: Not so much addressing the concerns/emoji. It's more about giving time to folks to review. Could the group use more time to gather more responses? If it had been 50/50 it feels yes, e should ex
```suggestion
* eP: We should make our best effort to address those thumbs down: Melvin and Hadrian. Melvin voiced his concerns; let's try to get Hadrian to explain. Once we clarify that, we're good to go. No problem with delaying, but still. I can reach out to Hadrian to get him to comment.
* SC: Not so much addressing the concerns/emoji. It's more about giving time to folks to review. Could the group use more time to gather more responses? If it had been 50/50 it feels yes, we should extend, but here we have more than most group's charters or even PRs having this number of approvals as well as long discussion to indicate it has been thoroughly discussed. That does not mean we need to stop it, but would another two weeks/month/year help? 
```

2023-07-26 17:16 UTC, TallTed commented on meetings/2023-07-26.md
> +* SC: This is not a standard for a CG, W3C has an understanding that if 5% of members approve a charter or a spec level transition it goes ahead. Not sure if it's written down somewhere. If we use th
```suggestion
* WT: I partially agree with eP on the fact that we could try to hear the people who reacted only through emoji, but also want to voice my concern that if they were there in the thread and had the possibility to comment but didn't feel the need to, just leaving emoji, I don't feel the urge to go after them and ask them what is it that they put an emoji for. That being said, I'm in favor of extending another week or two. 
* SC: This is not a standard for a CG; W3C has an understanding that if 5% of members approve a charter or a spec level transition, it goes ahead. Not sure if it's written down somewhere. If we use that measure, we are pretty much at that stage. So we have met the bar. The more reviews the better. 
```

2023-07-26 17:16 UTC, TallTed commented on meetings/2023-07-26.md
> +* PAC: This is a rough understanding, but yes, for a vote to be considered relevant we expect 5% of members to vote. Not sure if we can apply to CG. My understanding is that not all member organizati
```suggestion
* PAC: This is a rough understanding, but yes, for a vote to be considered relevant we expect 5% of members to vote. Not sure if we can apply to CG. My understanding is that not all member organizations are interested in all fields of work. Participants to a CG are expected to be all interested in the same topic. So not entirely comfortable to use that rule, but that being said, participation in CG is "cheaper" than W3C membership.. so many participants might be inactive and not expected to give their opinion. My point is I would not invoke that rule, but that doesn't mean the 5% rule isn't reasonable≤ for totally different reasons. 
```

2023-07-26 17:16 UTC, TallTed commented on meetings/2023-07-26.md
> +* WT: I did a count of active member over the past year on Matrix/Gitter, and there were about 50 people active. That would make the 13 respondents about a quarter. I have been waiting a few weeks in
```suggestion
* WT: I did a count of active members over the past year on Matrix/Gitter, and there were about 50 people active. That would make the 13 respondents about a quarter. I have been waiting a few weeks in order to see if others ask for changes. Maybe we can call it as is now, and if there are suggestions for changes, we can always make them later. 
```

2023-07-26 17:16 UTC, TallTed commented on meetings/2023-07-26.md
> +* SC: For the time being, I suggest everyone self-publishes their screencasts, and share the URLs with the CG. These are good assets. We can find a home to refer to those links. More details to follo
```suggestion
* SC: For the time being, I suggest everyone self-publish their screencasts, and share the URLs with the CG. These are good assets. We can find a home to refer to those links. More details to follow; for instance, make sure the URL is publicly archivable by the Internet Archive.
```

2023-07-26 18:23 UTC, VirginiaBalseiro commented on meetings/2023-07-26.md
> +* SC: PAC, do you think the amount of feedback, discussion, reviews, etc. looks healthy? The group has 272 people, compared to a WG charter or other CG charters, does it look good? Related to comment
```suggestion
* SC: PAC, do you think the amount of feedback, discussion, reviews, etc. looks healthy? The group has 272 people, compared to a WG charter or other CG charters, does it look good? Related to [comment by Ted](https://github.com/solid/process/pull/323#pullrequestreview-1547868732)
```

2023-07-27 03:53 UTC, woutermont requested changes

2023-07-27 03:53 UTC, woutermont commented on meetings/2023-07-26.md
> +* WT: I think that it's in scope but need to mention specifically shapes/vocab when the point is interoperability. Maybe mentioning as examples.
The way this was recorded seemed to be interpretable as exactly the opposite of what I meant.

```suggestion
* WT: I think that it's certainly in scope but only mentioning shapes/vocab is too specific when the point is interoperability. Maybe mention those as examples.
```

2023-07-28 06:24 UTC, merged