2023-10-24 meeting
solid/specification pull request #589
Opened 2023-10-25 15:04 UTC by elf-pavlik

2023-10-26 21:25 UTC, TallTed requested changes
Small stuff

2023-10-26 21:25 UTC, TallTed commented on meetings/2023-10-24.md
> +* AC: From the OIDC perspective I don't see advantages. I implemented OPs, RPs, RSs. I see why it would work for OAuth2; I don't see it needed for OIDC.
```suggestion
* AC: From the OIDC perspective, I don't see advantages. I implemented OPs, RPs, RSs. I see why it would work for OAuth2; I don't see it needed for OIDC.
```

2023-10-26 21:25 UTC, TallTed commented on meetings/2023-10-24.md
> +* RH: This is only one attack vector. With regards to malicious issuer being excluded by the RS.
```suggestion
* RH: This is only one attack vector, with regard to malicious issuer being excluded by the RS.
```

2023-10-26 21:25 UTC, TallTed commented on meetings/2023-10-24.md
> +* SL: The use case when an honest RP asks the user for an Issuer is a known user experience journey --- there are multiple ways a user could end up on the malicious OP
```suggestion
* AC: DPoP is now IETF RFC. It provides a way to bind the initial authorization step to the DPoP key used by the client. Issuer parameter coming from the issuer would be an ultimate step to resolving it.
* RH: This is probably also simpler than other ways of solving it. It also solves cross-site forgery attack. 
* eP: Two remarks — first, we can proceed with a Pull Request, with terms of either SHOULD or MUST. (At least SHOULD; we can discuss further in issue.) Second, the client is an honest agent; why would the client choose the malicious IdP?
* SL: The use case where an honest RP asks the user for an Issuer is a known user experience journey — there are multiple ways a user could end up on the malicious OP.
```

2023-10-27 10:00 UTC, csarven commented on meetings/2023-10-24.md
> +* Status: Draft
```suggestion
* Status: Published
```

2023-10-27 10:00 UTC, merged