Add section on decisions and processing-pull-requests
solid/specification pull request #590
Opened 2023-11-01 13:08 UTC by csarven

Further details decisions and processing PRs based on https://www.w3.org/2023/Process-20230612/#correction-classes

2023-11-01 14:43 UTC, elf-pavlik approved these changes

2023-11-02 17:51 UTC, TallTed requested changes
Language tweaks for clarity

2023-11-02 18:10 UTC, csarven commented on CONTRIBUTING.md
>  TRs might refer or make use of namespaces for specific functionality. The CG
Got this in https://github.com/solid/specification/commit/3c0b609dea054ca8698ce8d40637412584d9f2b5 , thanks!

2023-11-03 01:20 UTC, kjetilk approved these changes
LGTM

2023-11-17 15:58 UTC, csarven commented
Thank you @TallTed @elf-pavlik @kjetilk for reviewing.

Merging as per agreement in [2023-11-01 CG meeting](https://github.com/solid/specification/blob/main/meetings/2023-11-01.md#add-section-on-decisions-and-processing-pull-requests).

2023-11-17 15:58 UTC, merged