Add document status to guides, templates
solid/specification pull request #613
Opened 2024-01-10 13:22 UTC by csarven

This PR adds document status (modified and reason) to documents pertaining to the Solid CG. It follows a 2023-10-10 Solid CG meeting actions with the goal to clean-up / update references to CG's work. A related change was also made by https://github.com/solid/process/pull/331 .

2024-01-10 18:11 UTC, TallTed requested changes
a few grammar fixes

2024-01-10 18:11 UTC, TallTed commented on CONTRIBUTING.md
> +    <dd>This document is no longer effective and is no longer being updated here. For the latest information on the <a href="https://www.w3.org/groups/cg/solid/">W3C Solid Community Group</a>, please
```suggestion
    <dd>This document is no longer in effect and is no longer being updated here. For the latest information on the <a href="https://www.w3.org/groups/cg/solid/">W3C Solid Community Group</a>, please refer to its <a href="https://github.com/w3c-cg/solid/">repository</a>, <a href="https://www.w3.org/community/solid/charter/">charter</a>, and <a href="https://github.com/w3c-cg/solid/blob/main/CONTRIBUTING.md">contributing guidelines</a>.</dd>
```

2024-01-10 18:11 UTC, TallTed commented on meetings/README.md
> +    <dd>This document is no longer effective and is no longer being updated here. For the latest information on the <a href="https://www.w3.org/groups/cg/solid/">W3C Solid Community Group</a>, please
```suggestion
    <dd>This document is no longer in effect and is no longer being updated here. For the latest information on the <a href="https://www.w3.org/groups/cg/solid/">W3C Solid Community Group</a>, please refer to its <a href="https://github.com/w3c-cg/solid/">repository</a>, <a href="https://www.w3.org/community/solid/charter/">charter</a>, and <a href="https://github.com/w3c-cg/solid/blob/main/CONTRIBUTING.md">contributing guidelines</a>.</dd>
```

2024-01-10 18:11 UTC, TallTed commented on meetings/template.md
> +    <dd>This document is no longer effective and is no longer being updated here. For the latest information on the <a href="https://www.w3.org/groups/cg/solid/">W3C Solid Community Group</a>, please
```suggestion
    <dd>This document is no longer in effect and is no longer being updated here. For the latest information on the <a href="https://www.w3.org/groups/cg/solid/">W3C Solid Community Group</a>, please refer to its <a href="https://github.com/w3c-cg/solid/">repository</a>, <a href="https://www.w3.org/community/solid/charter/">charter</a>, and <a href="https://github.com/w3c-cg/solid/blob/main/CONTRIBUTING.md">contributing guidelines</a>.</dd>
```

2024-01-15 10:07 UTC, michielbdejong commented
This PR is on the [agenda for the 17 January CG Call](https://hackmd.io/1YFPpDmnR-GwpjTGugVXcw)

2024-01-17 01:00 UTC, elf-pavlik approved these changes

2024-01-17 14:10 UTC, VirginiaBalseiro approved these changes

2024-01-17 15:19 UTC, merged