Minutes for 2024-02-07 CG meeting
solid/specification pull request #622
Opened 2024-02-12 20:30 UTC by hzbarcea

2024-02-12 20:58 UTC, TallTed requested changes
typos

2024-02-12 20:58 UTC, TallTed commented on meetings/2024-02-07.md
> +* AC: From implementatione experience, the problems come to the composite nature of the containers. It gets complicated with conditional requsts using etags. Server Description seems like a simpler c
```suggestion
* AC: From implementation experience, the problems come to the composite nature of the containers. It gets complicated with conditional requests using eTags. Server Description seems like a simpler case.
```

2024-02-13 10:13 UTC, VirginiaBalseiro commented on meetings/2024-02-07.md
> +* Status: Draft
```suggestion
* Status: Published
```

2024-02-16 11:08 UTC, VirginiaBalseiro approved these changes

2024-02-23 09:27 UTC, merged