Minutes for 2024-02-14 CG meeting
solid/specification pull request #623
Opened 2024-02-14 02:44 UTC by hzbarcea

2024-02-14 18:01 UTC, TallTed requested changes
minor cleanup. note `???` block wants further fill-in.

2024-02-14 18:01 UTC, TallTed commented on meetings/2024-02-14.md
> +* eP: I'm using it in Description Resource, if app wants to show an icon for attachment etc.
```suggestion
* eP: I'm using it in Description Resource, if app wants to show an icon for attachment, etc.
```

2024-02-21 19:13 UTC, elf-pavlik commented on meetings/2024-02-14.md
> +* HZ: I recall that only one objection Sarven was considering valid. It was related to the chair selection. There was also something about the scope and the explainer. Tim has alredy written an expla
I don't think the name of the specific person is essential, so unless  @pchampin wants to fill it in, I would just go ahead and merge it with the ???

2024-02-22 09:45 UTC, VirginiaBalseiro approved these changes
Please squash when merging. Also, you can batch commit suggestions and add them all in one commit from the Files changed view instead of making individual commits.

2024-02-23 09:27 UTC, merged